name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      
      - name: Install tools
        run: |
          pip install black isort==5.6.4 flake8 mypy pytest
      
      - name: Run Black
        run: |
          black --check .

      - name: Run isort
        run: |
          isort --check-only --diff .

      - name: Run linter
        run: |
          pip install ruff
          ruff check .
      
      - name: Run Flake8
        run: |
          flake8 .

      - name: Run mypy
        run: |
          mypy .

      - name: Run tests
        run: |
          pytest